FROM fedora as base-image
RUN dnf -yqq upgrade
RUN dnf -yqq install httpd
EXPOSE 80:80
ENTRYPOINT /usr/sbin/httpd -DFOREGROUND

FROM base-image as website=1 
COPY website1.html /var/www/html/

FROM base-image as website=2
COPY website2.html /var/www/html/



